apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mytestapp
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  source:
    repoURL: oci://ghcr.io/srikanthhg   # OCI repo
    chart: my-test-chart                # Chart name
    targetRevision: 25.03.75            # Version
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
